@extends('layouts.admin')
@section('title',$order->order_number.' — Admin')
@section('page-title','Detail Pesanan')
@section('content')
<div class="space-y-6">
<section class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><div class="flex flex-wrap justify-between gap-4"><div><p class="text-sm font-bold text-amber-700">{{ $order->order_number }}</p><h2 class="text-2xl font-black">{{ $order->user->name }}</h2><p class="text-sm text-stone-500">{{ $order->user->email }} · {{ $order->recipient_phone }}</p></div><div class="flex gap-2"><x-status-badge :status="$order->payment_status"/><x-status-badge :status="$order->status"/></div></div></section>
<div class="grid gap-6 xl:grid-cols-[1fr_380px]"><div class="space-y-6"><section class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h3 class="text-xl font-black">Item pesanan</h3><div class="mt-4 divide-y divide-stone-100">@foreach($order->items as $item)<div class="flex justify-between gap-4 py-4"><div><b>{{ $item->product_name }}</b>@if($item->variant_label)<span class="ml-1 text-sm text-stone-500">({{ $item->variant_label }})</span>@endif<p class="text-sm text-stone-500">{{ $item->quantity }} × Rp {{ number_format($item->price,0,',','.') }}</p></div><b>Rp {{ number_format($item->subtotal,0,',','.') }}</b></div>@endforeach</div></section>
<section class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h3 class="text-xl font-black">Pembayaran</h3><p class="mt-2 text-sm">Metode: <b>{{ $order->payment_method_label }}</b></p>@if($order->payment_proof)<a href="{{ $order->payment_proof_url }}" target="_blank"><img src="{{ $order->payment_proof_url }}" class="mt-4 max-h-80 rounded-2xl border object-contain" alt="Bukti pembayaran"></a>@else<p class="mt-4 rounded-xl bg-stone-100 p-4 text-sm text-stone-500">Pembeli belum mengunggah bukti pembayaran.</p>@endif
@if($order->payment_status==='menunggu_verifikasi')<div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('admin.orders.verify-payment',$order) }}">@csrf @method('PATCH')<button class="btn-primary">Verifikasi pembayaran</button></form><form method="POST" action="{{ route('admin.orders.reject-payment',$order) }}" class="flex flex-wrap gap-2">@csrf @method('PATCH')<input name="payment_note" class="form-input max-w-xs" placeholder="Alasan penolakan" required><button class="rounded-xl bg-red-600 px-4 py-2 text-sm font-bold text-white">Tolak</button></form></div>@endif</section></div>
<aside class="space-y-6"><section class="rounded-3xl bg-stone-950 p-6 text-white"><h3 class="text-xl font-black">Ringkasan</h3><dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between"><dt>Subtotal</dt><dd>Rp {{ number_format($order->subtotal,0,',','.') }}</dd></div><div class="flex justify-between"><dt>Pengiriman</dt><dd>Rp {{ number_format($order->shipping_cost,0,',','.') }}</dd></div><div class="flex justify-between border-t border-stone-700 pt-3 text-lg font-black"><dt>Total</dt><dd>Rp {{ number_format($order->total,0,',','.') }}</dd></div></dl><div class="mt-5 text-sm text-stone-300"><p><b class="text-white">Metode:</b> {{ $order->delivery_label }}</p>@if($order->shipping_address)<p class="mt-2"><b class="text-white">Alamat:</b> {{ $order->shipping_address }}</p>@else<p class="mt-2"><b class="text-white">Lokasi ambil:</b> {{ config('kanrejawataa.pickup_address') }}</p>@endif</div></section>
<section class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h3 class="text-xl font-black">Perbarui status</h3><form method="POST" action="{{ route('admin.orders.status',$order) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<select name="status" class="form-input">@foreach($order->delivery_method==='pickup' ? ['diproses','siap_diambil','selesai'] : ['diproses','dikirim','selesai'] as $status)<option value="{{ $status }}" @selected($order->status===$status)>{{ ucwords(str_replace('_',' ',$status)) }}</option>@endforeach</select><textarea name="note" rows="3" class="form-input" placeholder="Catatan tracking (opsional)"></textarea><button class="btn-primary w-full">Simpan status</button></form></section></aside></div>
<section class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h3 class="text-xl font-black">Riwayat status</h3><div class="mt-4 space-y-4">@foreach($order->histories->sortBy('created_at') as $history)<div class="flex gap-3"><span class="mt-1 h-3 w-3 rounded-full bg-amber-500"></span><div><b>{{ ucwords(str_replace('_',' ',$history->status)) }}</b><p class="text-sm text-stone-500">{{ $history->created_at->format('d M Y H:i') }} @if($history->changer)· {{ $history->changer->name }}@endif</p>@if($history->note)<p class="text-sm">{{ $history->note }}</p>@endif</div></div>@endforeach</div></section>
</div>
@endsection
