@extends('layouts.account')
@section('title','Checkout — Kanrejawataa')
@section('account-content')
<form method="POST" action="{{ route('checkout.store') }}" x-data="{ delivery: '{{ old('delivery_method','pickup') }}' }" class="grid gap-6 xl:grid-cols-[1fr_360px]">@csrf
    <div class="space-y-6">
        <section class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h1 class="text-2xl font-black">Data penerima</h1><div class="mt-5 grid gap-4 sm:grid-cols-2"><div><label class="form-label">Nama penerima</label><input name="recipient_name" value="{{ old('recipient_name',auth()->user()->name) }}" class="form-input">@error('recipient_name')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label">Nomor telepon</label><input name="recipient_phone" value="{{ old('recipient_phone',auth()->user()->phone) }}" class="form-input">@error('recipient_phone')<p class="form-error">{{ $message }}</p>@enderror</div></div></section>
        <section class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Metode pengantaran</h2><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="option-card"><input type="radio" name="delivery_method" value="pickup" x-model="delivery"><span><b>Ambil sendiri</b><small>Ambil di {{ config('kanrejawataa.pickup_address') }}</small></span></label><label class="option-card"><input type="radio" name="delivery_method" value="delivery" x-model="delivery"><span><b>Dikirimkan</b><small>Biaya kirim Rp {{ number_format(config('kanrejawataa.delivery_fee'),0,',','.') }}</small></span></label></div><div x-show="delivery === 'delivery'" class="mt-4"><label class="form-label">Alamat pengiriman</label><textarea name="shipping_address" rows="4" class="form-input">{{ old('shipping_address',auth()->user()->address) }}</textarea>@error('shipping_address')<p class="form-error">{{ $message }}</p>@enderror</div></section>
        <section class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Metode pembayaran</h2><p class="mt-1 text-sm text-stone-500">Setelah checkout, unggah bukti pembayaran dari halaman detail pesanan.</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="option-card"><input type="radio" name="payment_method" value="bank_transfer" @checked(old('payment_method','bank_transfer')==='bank_transfer')><span><b>Transfer bank</b><small>{{ config('kanrejawataa.bank_name') }} {{ config('kanrejawataa.bank_account') }}</small></span></label><label class="option-card"><input type="radio" name="payment_method" value="qris" @checked(old('payment_method')==='qris')><span><b>QRIS</b><small>Pembayaran manual melalui QRIS</small></span></label></div><div class="mt-4"><label class="form-label">Catatan pesanan (opsional)</label><textarea name="notes" rows="3" class="form-input">{{ old('notes') }}</textarea></div></section>
    </div>
    <aside class="h-fit rounded-3xl bg-stone-950 p-6 text-white xl:sticky xl:top-24"><h2 class="text-xl font-black">Ringkasan pesanan</h2><div class="mt-5 space-y-3">@foreach($cart->items as $item)<div class="flex justify-between gap-3 text-sm"><span>{{ $item->variant->product->name }} @if($item->variant->label)({{ $item->variant->label }})@endif × {{ $item->quantity }}</span><b>Rp {{ number_format($item->subtotal,0,',','.') }}</b></div>@endforeach</div><div class="mt-5 border-t border-stone-700 pt-4"><div class="flex justify-between"><span>Subtotal</span><b>Rp {{ number_format($cart->subtotal,0,',','.') }}</b></div><div x-show="delivery === 'delivery'" class="mt-2 flex justify-between"><span>Pengiriman</span><b>Rp {{ number_format(config('kanrejawataa.delivery_fee'),0,',','.') }}</b></div></div><button class="mt-6 w-full rounded-2xl bg-amber-500 px-5 py-3 font-black text-stone-950 hover:bg-amber-400">Buat pesanan</button></aside>
</form>
@endsection
